name: "Login to ShopBack"
description: "Cache Playwright data and run the login script"
inputs:
  account:
    description: "ShopBack account email"
    required: true
  password:
    description: "ShopBack account password"
    required: true

runs:
  using: 'composite'
  steps:
    # 1. 快取 user_data 目錄，讓 Persistent Context 狀態可以跨次回復
    - name: Cache Playwright user data
      uses: actions/cache@v4
      with:
        path: state.json
        key: ${{ runner.os }}-playwright-state-json
        
    # 2. 執行 login.py 並帶入帳號密碼參數
    - name: Run Playwright login
      run: python executor/login.py -a ${{ inputs.account }} -p ${{ inputs.password }}
      shell: bash
