name: "Upload to google drive"

inputs:
  credential_json:
    description: "Google credential json"
    required: true
  folder_id:
    description: "Google drive folder id"
    required: true
  token_base64:
    description: "Token.pickle base64"
    required: true
  local_folder:
    description: "Local folder to be uploaded"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run upload
      run: |
        python executor/upload_google_drive.py \
        -j "${{ inputs.credential_json }}" \
        -f "${{ inputs.folder_id }}" \
        --token-base64 "${{ inputs.token_base64 }}" \
        -l "${{ inputs.local_folder }}"
      shell: bash
