name: CI Test

on:
  workflow_dispatch:
    inputs:
      notify_user_group:
        type: string

      notify_user:
        type: string
  
run-name: CI-Test

jobs:

  export-env:
    runs-on: ubuntu-latest
    environment: ScreenshotAutomation
    outputs:
      slack-channel-id: ${{ steps.set-vars.outputs.channel_id }}
    steps:
    - name: Export vars
      id: set-vars
      run: |
        echo "channel_id=${{ vars.SLACK_CHANNEL_ID }}" >> $GITHUB_OUTPUT
            
  success:
    needs: [export-env]
    uses: JohnsonWang13/github_action_tools/.github/workflows/Send_message_to_slack.yml@master
    with:
      is_success: true
      channel_id: ${{ needs.export-env.outputs.slack-channel-id }}
    secrets:
      SLACK_BOT_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
     
  fail:
    needs: [export-env]
    uses: JohnsonWang13/github_action_tools/.github/workflows/Send_message_to_slack.yml@master
    with:
      is_success: false
      channel_id: ${{ needs.export-env.outputs.slack-channel-id }}
      notify_user_group: ${{ inputs.notify_user_group }}
      notify_user: ${{ inputs.notify_user }}
    secrets:
      SLACK_BOT_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
