name: Full page screenshots

on:
  workflow_dispatch:
  
run-name: Full page screenshots

jobs:

  export-env:
    runs-on: ubuntu-latest
    environment: ScreenshotAutomation
    outputs:
    slack-channel-id: ${{ steps.set-vars.outputs.channel_id }}
    steps:
    - name: Export vars
      id: set-vars
      run: |
        echo "channel_id=${{ vars.SLACK_CHANNEL_ID }}" >> $GITHUB_OUTPUT
            
  success:
    uses: JohnsonWang13/github_action_tools/.github/workflows/Send_message_to_slack.yml@master
    with:
      is_success: true
      channel_id: ${{ needs.export-env.outputs.slack-channel-id }}
    secrets:
      SLACK_BOT_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
     
  fail:
    uses: JohnsonWang13/github_action_tools/.github/workflows/Send_message_to_slack.yml@master
    with:
      is_success: false
      channel_id: ${{ needs.export-env.outputs.slack-channel-id }}
    secrets:
      SLACK_BOT_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
