name: Full page screenshots

on:
  workflow_dispatch:
  
run-name: Full page screenshots

jobs:
  success:
    uses: JohnsonWang13/github_action_tools/.github/workflows/Send_message_to_slack.yml@master
    with:
      is_success: true
      channel_id: C09CQQXM5PW
    secrets: inherit
     
  fail:
    uses: JohnsonWang13/github_action_tools/.github/workflows/Send_message_to_slack.yml@master
    secrets: inherit
    with:
      is_success: false
      channel_id: C09CQQXM5PW
    secrets:
      SLACK_BOT_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
