name: Full page screenshots

on:
  workflow_dispatch:
  
run-name: Full page screenshots

jobs:
  login:
    environment: ScreenshotAutomation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: ./.github/actions/python-setup
        
      - name: Setup Font
        uses: ./.github/actions/font-setup
        
      - name: Screenshot travel-deals page
        run: |
            python executor/full_page_screenshot.py \
            -u 'https://www.shopback.com.tw/travel-deals' \
            -n 'campaign page_Travel'
            
      - name: Screenshot upsize--daily page
        run: |
            python executor/full_page_screenshot.py \
            -u 'https://www.shopback.com.tw/upsize--daily' \
            -n 'web store listing'
            
      - name: Screenshot new-merchants page
        run: |
            python executor/full_page_screenshot.py \
            -u 'https://www.shopback.com.tw/new-merchants' \
            -n 'web_newmerchant'

      - name: Screenshot seemore-coupon page
        run: |
            python executor/full_page_screenshot.py \
            -u 'https://www.shopback.com.tw/seemore-coupon-20' \
            -n 'web_coupon'
          
      - name: Upload screenshots to Google Drive
        uses: ./.github/actions/uploadToGoogleDrive
        with:
          credential_json: ${{ secrets.GOOGLE_CREDENTIAL_JSON }}
          folder_id: ${{ vars.UNKNOWNICON_FOLDER_ID }}
          token_base64: ${{ secrets.GOOGLE_TOKEN_PICKLE }}
          local_folder: ./full_page_screenshot
