name: Full page screenshots

on:
  schedule:
    - cron: '15 22 * * *'
    
  workflow_dispatch:
  
run-name: Full page screenshots

jobs:
  screenshots:
    environment: ScreenshotAutomation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Show runner public IP
        run: curl -s https://api.ipify.org

      - name: Setup Python
        uses: ./.github/actions/python-setup
        
      - name: Setup Font
        uses: ./.github/actions/font-setup
        
      - name: Cache Playwright user data
        uses: actions/cache@v4
        with:
          path: state.json
          key: ${{ runner.os }}-playwright-state-json
        
      - name: Screenshot travel-deals page
        run: |
            python executor/full_page_screenshot.py \
            -u 'https://www.shopback.com.tw/travel-deals' \
            -n 'campaign page_Travel' \
            -a "${{ secrets.SHOPBACK_ACCOUNT }}" \
            -p "${{ secrets.SHOPBACK_PASSWORD }}"
            
      - name: Screenshot upsize--daily page
        run: |
            python executor/full_page_screenshot.py \
            -u 'https://www.shopback.com.tw/upsize--daily' \
            -n 'web store listing' \
            -a "${{ secrets.SHOPBACK_ACCOUNT }}" \
            -p "${{ secrets.SHOPBACK_PASSWORD }}"
            
      - name: Screenshot new-merchants page
        run: |
            python executor/full_page_screenshot.py \
            -u 'https://www.shopback.com.tw/new-merchants' \
            -n 'web_newmerchant' \
            -a "${{ secrets.SHOPBACK_ACCOUNT }}" \
            -p "${{ secrets.SHOPBACK_PASSWORD }}"

      - name: Screenshot seemore-coupon page
        run: |
            python executor/full_page_screenshot.py \
            -u 'https://www.shopback.com.tw/seemore-coupon-20' \
            -n 'web_coupon' \
            -a "${{ secrets.SHOPBACK_ACCOUNT }}" \
            -p "${{ secrets.SHOPBACK_PASSWORD }}"
            
      - name: Cache token.pickle
        id: cache-token
        uses: actions/cache@v4
        with:
          path: token.pickle
          key: token-cache-v1-${{ hashFiles('token.pickle') }}
          restore-keys: |
            token-cache-v1-
          
      - name: Upload screenshots to Google Drive
        uses: ./.github/actions/uploadToGoogleDrive
        with:
          credential_json: ${{ secrets.GOOGLE_CREDENTIAL_JSON }}
          folder_id: ${{ vars.OTHER_FOLDER_ID }}
          token_base64: ${{ secrets.GOOGLE_TOKEN_PICKLE }}
          local_folder: ./full_page_screenshot
          
  export-env:
    runs-on: ubuntu-latest
    environment: ScreenshotAutomation
    outputs:
      slack-channel-id: ${{ steps.set-vars.outputs.channel_id }}
    steps:
    - name: Export vars
      id: set-vars
      run: |
        echo "channel_id=${{ vars.SLACK_CHANNEL_ID }}" >> $GITHUB_OUTPUT
            
  success:
    needs: [export-env, screenshots]
    if: success()
    uses: JohnsonWang13/github_action_tools/.github/workflows/Send_message_to_slack.yml@master
    with:
      is_success: true
      channel_id: ${{ needs.export-env.outputs.slack-channel-id }}
    secrets:
      SLACK_BOT_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
     
  fail:
    needs: [export-env, screenshots]
    if: failure()
    uses: JohnsonWang13/github_action_tools/.github/workflows/Send_message_to_slack.yml@master
    with:
      is_success: false
      channel_id: ${{ needs.export-env.outputs.slack-channel-id }}
    secrets:
      SLACK_BOT_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
